//! USDA (ASCII USD) exporter — write skeleton and animation to USDA format.
//!
//! Produces an ASCII `.usda` file (Universal Scene Description ASCII) from an
//! `ImportedModel` + optional motion data (global-space Mat4 frames).
//!
//! Exports:
//! - `SkelRoot` prim containing the `Skeleton` definition
//! - Joint hierarchy from `joint_names` / `parent_indices`
//! - Optional `SkelAnimation` with per-joint TRS timeSamples
//!
//! Meshes are included as `Mesh` prims with skinning bindings when available.

use std::io::Write;
use std::path::Path;

use glam::{Mat4, Vec3, Quat};

use crate::mesh::ImportedModel;

// ── Helper functions ─────────────────────────────────────────

/// Sanitize a name for use as a USD prim path (no spaces, no special chars).
fn sanitize_name(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for (i, c) in name.chars().enumerate() {
        if c.is_ascii_alphanumeric() || c == '_' {
            out.push(c);
        } else if c == ' ' || c == '-' || c == '.' {
            out.push('_');
        } else if i == 0 {
            out.push('_');
        }
        // skip other chars
    }
    if out.is_empty() {
        out.push_str("Joint");
    }
    // Ensure starts with letter or underscore
    if out.chars().next().map_or(true, |c| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}

/// Decompose a global-space Mat4 into (translation, rotation_quat, scale).
fn decompose_mat4(m: &Mat4) -> (Vec3, Quat, Vec3) {
    let (scale, rotation, translation) = m.to_scale_rotation_translation();
    (translation, rotation, scale)
}

/// Convert a global-space transform to local-space given the parent global transform.
fn global_to_local(global: &Mat4, parent_global: &Mat4) -> Mat4 {
    parent_global.inverse() * *global
}

/// Format a Vec3 as USD GfVec3f.
fn fmt_vec3f(v: Vec3) -> String {
    format!("({}, {}, {})", v.x, v.y, v.z)
}

/// Format a Quat as USD GfQuatf (w, x, y, z order for USD).
fn fmt_quatf(q: Quat) -> String {
    format!("({}, {}, {}, {})", q.w, q.x, q.y, q.z)
}

/// Format a Vec3 for half-precision display.
fn fmt_vec3h(v: Vec3) -> String {
    format!("({}, {}, {})", v.x, v.y, v.z)
}

/// Write indented line.
fn wln(out: &mut Vec<u8>, indent: usize, line: &str) {
    for _ in 0..indent {
        out.extend_from_slice(b"    ");
    }
    out.extend_from_slice(line.as_bytes());
    out.extend_from_slice(b"\n");
}

// ── Joint path helpers ───────────────────────────────────────

/// Build the full joint path token for each joint.
/// e.g., ["Hips", "Hips/Spine", "Hips/Spine/Chest", ...]
fn build_joint_paths(joint_names: &[String], parent_indices: &[i32]) -> Vec<String> {
    let sanitized: Vec<String> = joint_names.iter().map(|n| sanitize_name(n)).collect();
    let mut paths = vec![String::new(); joint_names.len()];

    for i in 0..joint_names.len() {
        let pi = parent_indices[i];
        if pi < 0 || pi as usize >= i {
            // Root joint
            paths[i] = sanitized[i].clone();
        } else {
            paths[i] = format!("{}/{}", paths[pi as usize], sanitized[i]);
        }
    }
    paths
}

// ── Main export function ─────────────────────────────────────

/// Export an `ImportedModel` with optional animation to USDA format.
///
/// # Arguments
/// - `path` — Destination `.usda` file path.
/// - `model` — Model with skeleton hierarchy.
/// - `frames` — Optional animation frames (global-space Mat4 per joint per frame).
/// - `framerate` — Frames per second.
pub fn export_usd(
    path: &Path,
    model: &ImportedModel,
    frames: Option<&Vec<Vec<Mat4>>>,
    framerate: f32,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut out: Vec<u8> = Vec::with_capacity(64 * 1024);

    let model_name = sanitize_name(&model.name);
    let num_joints = model.joint_names.len();
    let joint_paths = build_joint_paths(&model.joint_names, &model.parent_indices);

    let has_animation = frames.map_or(false, |f| !f.is_empty());
    let num_frames = frames.map_or(0, |f| f.len());
    let fps = framerate as f64;

    // ── File header ──────────────────────────────────
    wln(&mut out, 0, "#usda 1.0");
    wln(&mut out, 0, "(");
    wln(&mut out, 1, "doc = \"Generated by AI4Animation Engine\"");
    wln(&mut out, 1, &format!("metersPerUnit = 1"));
    wln(&mut out, 1, &format!("upAxis = \"Y\""));
    if has_animation {
        wln(&mut out, 1, &format!("startTimeCode = 0"));
        wln(&mut out, 1, &format!("endTimeCode = {}", num_frames.saturating_sub(1)));
        wln(&mut out, 1, &format!("timeCodesPerSecond = {}", fps));
        wln(&mut out, 1, &format!("framesPerSecond = {}", fps));
    }
    wln(&mut out, 0, ")");
    wln(&mut out, 0, "");

    // ── SkelRoot ─────────────────────────────────────
    wln(&mut out, 0, &format!("def SkelRoot \"{}\" (", model_name));
    wln(&mut out, 1, "kind = \"component\"");
    wln(&mut out, 0, ")");
    wln(&mut out, 0, "{");

    // ── Skeleton definition ──────────────────────────
    wln(&mut out, 1, "def Skeleton \"Skeleton\"");
    wln(&mut out, 1, "{");

    // joints attribute
    {
        let mut joints_str = String::from("uniform token[] joints = [");
        for (i, jp) in joint_paths.iter().enumerate() {
            if i > 0 { joints_str.push_str(", "); }
            joints_str.push_str(&format!("\"{}\"", jp));
        }
        joints_str.push(']');
        wln(&mut out, 2, &joints_str);
    }

    // Bind transforms (rest pose) — local-space transforms at bind time
    {
        wln(&mut out, 2, "uniform matrix4d[] bindTransforms = [");
        for i in 0..num_joints {
            let bind = Mat4::IDENTITY; // Default bind pose = identity (joints defined in parent space)
            let m = bind;
            let comma = if i + 1 < num_joints { "," } else { "" };
            wln(&mut out, 3, &format!(
                "( ({}, {}, {}, {}), ({}, {}, {}, {}), ({}, {}, {}, {}), ({}, {}, {}, {}) ){}",
                m.x_axis.x, m.x_axis.y, m.x_axis.z, m.x_axis.w,
                m.y_axis.x, m.y_axis.y, m.y_axis.z, m.y_axis.w,
                m.z_axis.x, m.z_axis.y, m.z_axis.z, m.z_axis.w,
                m.w_axis.x, m.w_axis.y, m.w_axis.z, m.w_axis.w,
                comma,
            ));
        }
        wln(&mut out, 2, "]");
    }

    // Rest transforms (same as bind for our use case)
    {
        wln(&mut out, 2, "uniform matrix4d[] restTransforms = [");
        for i in 0..num_joints {
            let m = Mat4::IDENTITY;
            let comma = if i + 1 < num_joints { "," } else { "" };
            wln(&mut out, 3, &format!(
                "( ({}, {}, {}, {}), ({}, {}, {}, {}), ({}, {}, {}, {}), ({}, {}, {}, {}) ){}",
                m.x_axis.x, m.x_axis.y, m.x_axis.z, m.x_axis.w,
                m.y_axis.x, m.y_axis.y, m.y_axis.z, m.y_axis.w,
                m.z_axis.x, m.z_axis.y, m.z_axis.z, m.z_axis.w,
                m.w_axis.x, m.w_axis.y, m.w_axis.z, m.w_axis.w,
                comma,
            ));
        }
        wln(&mut out, 2, "]");
    }

    wln(&mut out, 1, "}");
    wln(&mut out, 1, "");

    // ── SkelAnimation ────────────────────────────────
    if has_animation {
        let anim_frames = frames.unwrap();

        wln(&mut out, 1, "def SkelAnimation \"Animation\"");
        wln(&mut out, 1, "{");

        // joints attribute (same order)
        {
            let mut joints_str = String::from("uniform token[] joints = [");
            for (i, jp) in joint_paths.iter().enumerate() {
                if i > 0 { joints_str.push_str(", "); }
                joints_str.push_str(&format!("\"{}\"", jp));
            }
            joints_str.push(']');
            wln(&mut out, 2, &joints_str);
        }

        // Convert global-space frames to local-space TRS
        // translations timeSamples
        wln(&mut out, 2, "float3[] translations.timeSamples = {");
        for (frame_idx, frame) in anim_frames.iter().enumerate() {
            let time = frame_idx as f64;
            let mut values = String::new();
            values.push('[');
            for (j, global_tf) in frame.iter().enumerate() {
                let local = if model.parent_indices[j] >= 0 {
                    let pi = model.parent_indices[j] as usize;
                    if pi < frame.len() {
                        global_to_local(global_tf, &frame[pi])
                    } else {
                        *global_tf
                    }
                } else {
                    *global_tf
                };
                let (t, _r, _s) = decompose_mat4(&local);
                if j > 0 { values.push_str(", "); }
                values.push_str(&fmt_vec3f(t));
            }
            values.push(']');
            let comma = if frame_idx + 1 < num_frames { "," } else { "" };
            wln(&mut out, 3, &format!("{}: {}{}", time, values, comma));
        }
        wln(&mut out, 2, "}");

        // rotations timeSamples
        wln(&mut out, 2, "quatf[] rotations.timeSamples = {");
        for (frame_idx, frame) in anim_frames.iter().enumerate() {
            let time = frame_idx as f64;
            let mut values = String::new();
            values.push('[');
            for (j, global_tf) in frame.iter().enumerate() {
                let local = if model.parent_indices[j] >= 0 {
                    let pi = model.parent_indices[j] as usize;
                    if pi < frame.len() {
                        global_to_local(global_tf, &frame[pi])
                    } else {
                        *global_tf
                    }
                } else {
                    *global_tf
                };
                let (_t, r, _s) = decompose_mat4(&local);
                if j > 0 { values.push_str(", "); }
                values.push_str(&fmt_quatf(r));
            }
            values.push(']');
            let comma = if frame_idx + 1 < num_frames { "," } else { "" };
            wln(&mut out, 3, &format!("{}: {}{}", time, values, comma));
        }
        wln(&mut out, 2, "}");

        // scales timeSamples
        wln(&mut out, 2, "half3[] scales.timeSamples = {");
        for (frame_idx, frame) in anim_frames.iter().enumerate() {
            let time = frame_idx as f64;
            let mut values = String::new();
            values.push('[');
            for (j, global_tf) in frame.iter().enumerate() {
                let local = if model.parent_indices[j] >= 0 {
                    let pi = model.parent_indices[j] as usize;
                    if pi < frame.len() {
                        global_to_local(global_tf, &frame[pi])
                    } else {
                        *global_tf
                    }
                } else {
                    *global_tf
                };
                let (_t, _r, s) = decompose_mat4(&local);
                if j > 0 { values.push_str(", "); }
                values.push_str(&fmt_vec3h(s));
            }
            values.push(']');
            let comma = if frame_idx + 1 < num_frames { "," } else { "" };
            wln(&mut out, 3, &format!("{}: {}{}", time, values, comma));
        }
        wln(&mut out, 2, "}");

        wln(&mut out, 1, "}");
        wln(&mut out, 1, "");
    }

    // ── Mesh prims ───────────────────────────────────
    for (mesh_idx, mesh) in model.meshes.iter().enumerate() {
        let mesh_name = format!("Mesh_{}", mesh_idx);
        wln(&mut out, 1, &format!("def Mesh \"{}\" (", mesh_name));
        wln(&mut out, 2, "prepend apiSchemas = [\"SkelBindingAPI\"]");
        wln(&mut out, 1, ")");
        wln(&mut out, 1, "{");

        // Points
        wln(&mut out, 2, &format!("int[] faceVertexCounts = [{}]",
            (0..mesh.indices.len() / 3).map(|_| "3").collect::<Vec<_>>().join(", ")
        ));

        let indices_str: Vec<String> = mesh.indices.iter().map(|i| i.to_string()).collect();
        wln(&mut out, 2, &format!("int[] faceVertexIndices = [{}]", indices_str.join(", ")));

        // Write points
        wln(&mut out, 2, "point3f[] points = [");
        for (vi, v) in mesh.vertices.iter().enumerate() {
            let comma = if vi + 1 < mesh.vertices.len() { "," } else { "" };
            wln(&mut out, 3, &format!("({}, {}, {}){}", v.x, v.y, v.z, comma));
        }
        wln(&mut out, 2, "]");

        // Normals
        if !mesh.normals.is_empty() {
            wln(&mut out, 2, "normal3f[] normals = [");
            for (ni, n) in mesh.normals.iter().enumerate() {
                let comma = if ni + 1 < mesh.normals.len() { "," } else { "" };
                wln(&mut out, 3, &format!("({}, {}, {}){}", n.x, n.y, n.z, comma));
            }
            wln(&mut out, 2, "]");
            wln(&mut out, 2, "uniform token normals:interpolation = \"vertex\"");
        }

        // UVs
        if !mesh.texcoords.is_empty() {
            wln(&mut out, 2, "texCoord2f[] primvars:st = [");
            for (ti, t) in mesh.texcoords.iter().enumerate() {
                let comma = if ti + 1 < mesh.texcoords.len() { "," } else { "" };
                wln(&mut out, 3, &format!("({}, {}){}", t.x, t.y, comma));
            }
            wln(&mut out, 2, "]");
            wln(&mut out, 2, "uniform token primvars:st:interpolation = \"vertex\"");
        }

        // Skeleton binding
        if num_joints > 0 {
            wln(&mut out, 2, "rel skel:skeleton = </Skeleton>");
            if has_animation {
                wln(&mut out, 2, "rel skel:animationSource = </Animation>");
            }

            // Joint indices and weights for skinning
            if !mesh.bone_indices.is_empty() && !mesh.bone_weights.is_empty() {
                let elem_size = 4;
                wln(&mut out, 2, &format!("int[] primvars:skel:jointIndices.elementSize = {}", elem_size));
                let mut ji_vals = Vec::new();
                for bi in &mesh.bone_indices {
                    for &idx in bi {
                        ji_vals.push(idx.to_string());
                    }
                }
                wln(&mut out, 2, &format!("int[] primvars:skel:jointIndices = [{}]", ji_vals.join(", ")));
                wln(&mut out, 2, "uniform token primvars:skel:jointIndices:interpolation = \"vertex\"");

                let mut jw_vals = Vec::new();
                for bw in &mesh.bone_weights {
                    for &w in bw {
                        jw_vals.push(format!("{}", w));
                    }
                }
                wln(&mut out, 2, &format!("float[] primvars:skel:jointWeights = [{}]", jw_vals.join(", ")));
                wln(&mut out, 2, "uniform token primvars:skel:jointWeights:interpolation = \"vertex\"");
            }
        }

        wln(&mut out, 1, "}");
        wln(&mut out, 1, "");
    }

    // Close SkelRoot
    wln(&mut out, 0, "}");

    // Write to file
    let mut file = std::fs::File::create(path)?;
    file.write_all(&out)?;

    Ok(())
}

// ── USDA Importer ────────────────────────────────────────────

/// Import a USDA file into an `ImportedModel`.
///
/// Supports:
/// - Skeleton joint hierarchy (from `joints` attribute)
/// - SkelAnimation TRS timeSamples
/// - Basic Mesh prims (points, normals, indices)
///
/// This is a lightweight parser for the USDA ASCII subset we export.
#[allow(unused_assignments)]
pub fn import_usd(path: &Path) -> Result<ImportedModel, Box<dyn std::error::Error>> {
    let content = std::fs::read_to_string(path)?;
    let lines: Vec<&str> = content.lines().collect();

    let mut joint_paths: Vec<String> = Vec::new();
    let mut joint_names: Vec<String> = Vec::new();
    let mut parent_indices: Vec<i32> = Vec::new();
    let mut framerate: f32 = 30.0;
    let mut model_name = "USD_Model".to_string();

    // Translation, rotation, scale timeSamples per frame
    let mut translation_frames: Vec<Vec<Vec3>> = Vec::new();
    let mut rotation_frames: Vec<Vec<Quat>> = Vec::new();
    let mut scale_frames: Vec<Vec<Vec3>> = Vec::new();

    // Mesh data
    let mut vertices: Vec<Vec3> = Vec::new();
    let mut normals: Vec<Vec3> = Vec::new();
    let mut indices: Vec<u32> = Vec::new();

    let mut i = 0;
    while i < lines.len() {
        let line = lines[i].trim();

        // Parse framesPerSecond
        if line.starts_with("framesPerSecond") || line.starts_with("timeCodesPerSecond") {
            if let Some(val) = extract_float_value(line) {
                framerate = val as f32;
            }
        }

        // Parse SkelRoot name
        if line.starts_with("def SkelRoot") {
            if let Some(name) = extract_quoted(line) {
                model_name = name;
            }
        }

        // Parse joints array
        if line.contains("token[] joints") && line.contains('[') {
            let full = collect_bracketed_content(&lines, &mut i);
            joint_paths = parse_string_array(&full);
            // Derive names and parent indices from paths
            joint_names.clear();
            parent_indices.clear();
            for jp in &joint_paths {
                let parts: Vec<&str> = jp.split('/').collect();
                joint_names.push(parts.last().unwrap_or(&"Joint").to_string());
                if parts.len() <= 1 {
                    parent_indices.push(-1);
                } else {
                    // Find parent path
                    let parent_path = parts[..parts.len() - 1].join("/");
                    let pi = joint_paths.iter().position(|p| p == &parent_path)
                        .map(|idx| idx as i32)
                        .unwrap_or(-1);
                    parent_indices.push(pi);
                }
            }
        }

        // Parse translations timeSamples
        if line.contains("translations.timeSamples") && line.contains('{') {
            i += 1;
            while i < lines.len() {
                let tl = lines[i].trim();
                if tl == "}" { break; }
                // Parse "time: [vec3, vec3, ...]"
                if let Some(colon_pos) = tl.find(':') {
                    let array_part = &tl[colon_pos + 1..];
                    let vecs = parse_vec3_array(array_part);
                    if !vecs.is_empty() {
                        translation_frames.push(vecs);
                    }
                }
                i += 1;
            }
        }

        // Parse rotations timeSamples
        if line.contains("rotations.timeSamples") && line.contains('{') {
            i += 1;
            while i < lines.len() {
                let tl = lines[i].trim();
                if tl == "}" { break; }
                if let Some(colon_pos) = tl.find(':') {
                    let array_part = &tl[colon_pos + 1..];
                    let quats = parse_quatf_array(array_part);
                    if !quats.is_empty() {
                        rotation_frames.push(quats);
                    }
                }
                i += 1;
            }
        }

        // Parse scales timeSamples
        if line.contains("scales.timeSamples") && line.contains('{') {
            i += 1;
            while i < lines.len() {
                let tl = lines[i].trim();
                if tl == "}" { break; }
                if let Some(colon_pos) = tl.find(':') {
                    let array_part = &tl[colon_pos + 1..];
                    let vecs = parse_vec3_array(array_part);
                    if !vecs.is_empty() {
                        scale_frames.push(vecs);
                    }
                }
                i += 1;
            }
        }

        // Parse mesh points
        if line.contains("point3f[] points") && line.contains('[') {
            let full = collect_bracketed_content(&lines, &mut i);
            vertices = parse_vec3_array(&full);
        }

        // Parse mesh normals
        if line.contains("normal3f[] normals") && line.contains('[') {
            let full = collect_bracketed_content(&lines, &mut i);
            normals = parse_vec3_array(&full);
        }

        // Parse face vertex indices
        if line.contains("faceVertexIndices") && line.contains('[') {
            let full = collect_bracketed_content(&lines, &mut i);
            indices = parse_int_array(&full);
        }

        i += 1;
    }

    // Build animation frames from TRS timeSamples (convert local → global)
    let animation_frames = if !translation_frames.is_empty() {
        let num_anim_frames = translation_frames.len();
        let num_j = joint_names.len();
        let mut frames: Vec<Vec<Mat4>> = Vec::with_capacity(num_anim_frames);

        for f in 0..num_anim_frames {
            let mut global_transforms = vec![Mat4::IDENTITY; num_j];
            for j in 0..num_j {
                let t = translation_frames.get(f)
                    .and_then(|fr| fr.get(j))
                    .copied()
                    .unwrap_or(Vec3::ZERO);
                let r = rotation_frames.get(f)
                    .and_then(|fr| fr.get(j))
                    .copied()
                    .unwrap_or(Quat::IDENTITY);
                let s = scale_frames.get(f)
                    .and_then(|fr| fr.get(j))
                    .copied()
                    .unwrap_or(Vec3::ONE);

                let local = Mat4::from_scale_rotation_translation(s, r, t);
                let pi = parent_indices[j];
                let global = if pi >= 0 && (pi as usize) < num_j {
                    global_transforms[pi as usize] * local
                } else {
                    local
                };
                global_transforms[j] = global;
            }
            frames.push(global_transforms);
        }

        Some(crate::mesh::AnimationData { frames, framerate })
    } else {
        None
    };

    // Build mesh
    let meshes = if !vertices.is_empty() {
        vec![crate::mesh::ImportedMesh {
            vertices,
            normals,
            texcoords: Vec::new(),
            indices,
            bone_indices: Vec::new(),
            bone_weights: Vec::new(),
            texture: None,
            normal_map: None,
            metallic_roughness_map: None,
            emission_map: None,
            material_index: 0,
        }]
    } else {
        Vec::new()
    };

    Ok(ImportedModel {
        name: model_name,
        meshes,
        skin: None,
        joint_names,
        parent_indices,
        animation_frames,
    })
}

// ── Parsing helpers ──────────────────────────────────────────

/// Extract a float value from a line like "framesPerSecond = 30".
fn extract_float_value(line: &str) -> Option<f64> {
    if let Some(eq_pos) = line.find('=') {
        line[eq_pos + 1..].trim().trim_end_matches(')').trim().parse::<f64>().ok()
    } else {
        None
    }
}

/// Extract a quoted string from a line like `def SkelRoot "MyModel"`.
fn extract_quoted(line: &str) -> Option<String> {
    let start = line.find('"')? + 1;
    let end = line[start..].find('"')? + start;
    Some(line[start..end].to_string())
}

/// Collect everything between [ and ] potentially spanning multiple lines.
fn collect_bracketed_content(lines: &[&str], i: &mut usize) -> String {
    let mut result = String::new();
    let line = lines[*i];
    if let Some(bracket_start) = line.find('[') {
        result.push_str(&line[bracket_start..]);
    }
    // Check if the bracket is already closed on this line
    if result.contains(']') {
        return result;
    }
    *i += 1;
    while *i < lines.len() {
        let l = lines[*i].trim();
        result.push(' ');
        result.push_str(l);
        if l.contains(']') {
            break;
        }
        *i += 1;
    }
    result
}

/// Parse a string array like `["Hips", "Hips/Spine"]`.
fn parse_string_array(s: &str) -> Vec<String> {
    let mut result = Vec::new();
    let mut in_quote = false;
    let mut current = String::new();
    for c in s.chars() {
        match c {
            '"' => {
                if in_quote {
                    result.push(current.clone());
                    current.clear();
                }
                in_quote = !in_quote;
            }
            _ if in_quote => current.push(c),
            _ => {}
        }
    }
    result
}

/// Parse a Vec3 array from a string like `[(1, 2, 3), (4, 5, 6)]`.
fn parse_vec3_array(s: &str) -> Vec<Vec3> {
    let mut result = Vec::new();
    let mut depth = 0;
    let mut current = String::new();

    for c in s.chars() {
        match c {
            '(' => {
                depth += 1;
                if depth == 1 {
                    current.clear();
                }
            }
            ')' => {
                depth -= 1;
                if depth == 0 {
                    // Parse "x, y, z"
                    let parts: Vec<f32> = current.split(',')
                        .filter_map(|p| p.trim().parse::<f32>().ok())
                        .collect();
                    if parts.len() >= 3 {
                        result.push(Vec3::new(parts[0], parts[1], parts[2]));
                    }
                }
            }
            _ if depth >= 1 => current.push(c),
            _ => {}
        }
    }
    result
}

/// Parse a Quat array from `[(w, x, y, z), ...]`.
fn parse_quatf_array(s: &str) -> Vec<Quat> {
    let mut result = Vec::new();
    let mut depth = 0;
    let mut current = String::new();

    for c in s.chars() {
        match c {
            '(' => {
                depth += 1;
                if depth == 1 {
                    current.clear();
                }
            }
            ')' => {
                depth -= 1;
                if depth == 0 {
                    let parts: Vec<f32> = current.split(',')
                        .filter_map(|p| p.trim().parse::<f32>().ok())
                        .collect();
                    if parts.len() >= 4 {
                        // USD: (w, x, y, z) → glam Quat::from_xyzw(x, y, z, w)
                        result.push(Quat::from_xyzw(parts[1], parts[2], parts[3], parts[0]));
                    }
                }
            }
            _ if depth >= 1 => current.push(c),
            _ => {}
        }
    }
    result
}

/// Parse int array from `[0, 1, 2, 3]`.
fn parse_int_array(s: &str) -> Vec<u32> {
    s.chars()
        .filter(|c| c.is_ascii_digit() || *c == ',' || *c == ' ')
        .collect::<String>()
        .split(',')
        .filter_map(|p| p.trim().parse::<u32>().ok())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use glam::Mat4;

    #[test]
    fn test_sanitize_name() {
        assert_eq!(sanitize_name("Hips"), "Hips");
        assert_eq!(sanitize_name("Left Arm"), "Left_Arm");
        assert_eq!(sanitize_name("123"), "_123");
        assert_eq!(sanitize_name("bone.001"), "bone_001");
    }

    #[test]
    fn test_build_joint_paths() {
        let names = vec!["Hips".into(), "Spine".into(), "LeftLeg".into()];
        let parents = vec![-1, 0, 0];
        let paths = build_joint_paths(&names, &parents);
        assert_eq!(paths[0], "Hips");
        assert_eq!(paths[1], "Hips/Spine");
        assert_eq!(paths[2], "Hips/LeftLeg");
    }

    #[test]
    fn test_export_empty() {
        let model = ImportedModel {
            name: "Test".into(),
            meshes: Vec::new(),
            skin: None,
            joint_names: Vec::new(),
            parent_indices: Vec::new(),
            animation_frames: None,
        };
        let dir = std::env::temp_dir();
        let path = dir.join("test_empty.usda");
        export_usd(&path, &model, None, 30.0).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("#usda 1.0"));
        assert!(content.contains("def SkelRoot \"Test\""));
        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn test_export_with_skeleton() {
        let model = ImportedModel {
            name: "Skeleton".into(),
            meshes: Vec::new(),
            skin: None,
            joint_names: vec!["Hips".into(), "Spine".into(), "Head".into()],
            parent_indices: vec![-1, 0, 1],
            animation_frames: None,
        };
        let dir = std::env::temp_dir();
        let path = dir.join("test_skel.usda");
        export_usd(&path, &model, None, 30.0).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("\"Hips\""));
        assert!(content.contains("\"Hips/Spine\""));
        assert!(content.contains("\"Hips/Spine/Head\""));
        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn test_export_with_animation() {
        let model = ImportedModel {
            name: "Animated".into(),
            meshes: Vec::new(),
            skin: None,
            joint_names: vec!["Root".into(), "Child".into()],
            parent_indices: vec![-1, 0],
            animation_frames: None,
        };
        let frames = vec![
            vec![Mat4::IDENTITY, Mat4::from_translation(Vec3::new(0.0, 1.0, 0.0))],
            vec![
                Mat4::from_translation(Vec3::new(1.0, 0.0, 0.0)),
                Mat4::from_translation(Vec3::new(1.0, 1.0, 0.0)),
            ],
        ];
        let dir = std::env::temp_dir();
        let path = dir.join("test_anim.usda");
        export_usd(&path, &model, Some(&frames), 30.0).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("SkelAnimation"));
        assert!(content.contains("translations.timeSamples"));
        assert!(content.contains("rotations.timeSamples"));
        assert!(content.contains("framesPerSecond = 30"));
        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn test_roundtrip() {
        let model = ImportedModel {
            name: "RoundTrip".into(),
            meshes: Vec::new(),
            skin: None,
            joint_names: vec!["Root".into(), "Child".into()],
            parent_indices: vec![-1, 0],
            animation_frames: None,
        };
        let frames = vec![
            vec![Mat4::IDENTITY, Mat4::from_translation(Vec3::new(0.0, 1.0, 0.0))],
            vec![
                Mat4::from_translation(Vec3::new(1.0, 0.0, 0.0)),
                Mat4::from_translation(Vec3::new(1.0, 1.5, 0.0)),
            ],
        ];
        let dir = std::env::temp_dir();
        let path = dir.join("test_roundtrip.usda");

        // Export
        export_usd(&path, &model, Some(&frames), 24.0).unwrap();

        // Import back
        let imported = import_usd(&path).unwrap();
        assert_eq!(imported.joint_names.len(), 2);
        assert_eq!(imported.joint_names[0], "Root");
        assert_eq!(imported.joint_names[1], "Child");
        assert_eq!(imported.parent_indices[0], -1);
        assert_eq!(imported.parent_indices[1], 0);

        // Animation should have been imported
        let anim = imported.animation_frames.as_ref().expect("animation should exist");
        assert_eq!(anim.frames.len(), 2); // 2 frames
        assert_eq!(anim.frames[0].len(), 2); // 2 joints

        // Check root transform in frame 1 — should be near (1, 0, 0) translation
        let root_f1 = anim.frames[1][0];
        let root_pos = Vec3::new(root_f1.w_axis.x, root_f1.w_axis.y, root_f1.w_axis.z);
        assert!((root_pos - Vec3::new(1.0, 0.0, 0.0)).length() < 0.01,
            "Root position at frame 1 should be near (1,0,0), got {:?}", root_pos);

        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn test_parse_string_array() {
        let input = r#"["Hips", "Hips/Spine", "Hips/Spine/Head"]"#;
        let result = parse_string_array(input);
        assert_eq!(result, vec!["Hips", "Hips/Spine", "Hips/Spine/Head"]);
    }

    #[test]
    fn test_parse_vec3_array() {
        let input = "[(1, 2, 3), (4, 5, 6)]";
        let result = parse_vec3_array(input);
        assert_eq!(result.len(), 2);
        assert!((result[0] - Vec3::new(1.0, 2.0, 3.0)).length() < 0.001);
        assert!((result[1] - Vec3::new(4.0, 5.0, 6.0)).length() < 0.001);
    }
}
